### ISSUE TITLE
Mutable global state antipattern?

### ISSUE THREAD

**Issue by gim-** [fluxroot/flux#84]
```java
import com.fluxchess.flux.board.Hex88Board;
import com.fluxchess.flux.move.IntMove;
import com.fluxchess.jcpi.models.GenericBoard;
import com.fluxchess.jcpi.models.GenericMove;
import com.fluxchess.jcpi.models.IllegalNotationException;
import org.junit.Assert;

public class Main {

    public static void main(String[] args) throws IllegalNotationException {
        // First board
        GenericBoard board1 = new GenericBoard(GenericBoard.STANDARDSETUP);
        Hex88Board hex88Board1 = new Hex88Board(board1);

        // Second board
        GenericBoard board2 = new GenericBoard(GenericBoard.STANDARDSETUP);
        Hex88Board hex88Board2 = new Hex88Board(board2);

        // Make a move on the first board, which changes its state
        hex88Board1.makeMove(IntMove.convertMove(new GenericMove("g1f3"), hex88Board1));

        // At this point I assume that only first board positions are changed,
        // though that doesn't seem to be the case
        System.out.println(hex88Board1.toString().split(" ")[0]);
        System.out.println(hex88Board2.toString().split(" ")[0]);
        Assert.assertNotEquals(
                hex88Board1.toString().split(" ")[0],
                hex88Board2.toString().split(" ")[0]
        );
    }
}
```
The output:
```
rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R
rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R
Exception in thread "main" java.lang.AssertionError: Values should be different. Actual: rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at Main.main(Main.java:26)
```

**Comment by gim-** [comment]
To avoid issues caused by this it looks like one should operate only with GenericBoard and use Hex88Board as a temporary wrapper to do the job and get a new GenericBoard instance from it afterwards. Still, global mutable state is never a good idea and is not really necessary.

**Comment by fluxroot** [comment]
Yeah, I was young and careless. :) Now I'm old and grey and hopefully a little bit wiser. If I ever rewrite this engine, I promise I will do better.

I'll close this issue as it is not relevant anymore. Feel free to reopen.
